@extends('layouts.front')
@section('title')
        Privacy Policy
    @endsection
@section('content')
<div class="py-3   border-top">
    <div class="container">
        <div class="mb-0">
            <a href="{{url('/')}}">
                Home
            </a>/
            <a href="{{url('/privacy-policy')}}">
               Privacy Policy
            </a>
        </div>
    </div>
</div>
<div class="container">
<div class="row">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left">
                                    <h2 class="fs-28 f-700 mb-5">Privacy Policy</h2>
                                    <p class="mb-0">This document is an electronic record in terms of Information
                                        Technology Act, 2000 and rules there under as applicable and the amended
                                        provisions pertaining to electronic records in various statutes as amended by
                                        the Information Technology Act, 2000. This electronic record is generated by a
                                        computer system and does not require any physical or digital signatures. For the
                                        purpose of this Privacy Policy, wherever the context so requires "You" or "User"
                                        shall mean any natural or legal person who visits our platform, either just for
                                        the purpose of browsing www.washingxpress.com (our “Website”) website or engages
                                        to buy our service. The term "We", "Us", "Our", “Washing Xpress” shall mean
                                        Rondella Marketing Private Limited.
                                        As a company, we fully understand and respect that the information you are
                                        sharing with us is private in nature and needs to be duly safeguarded. To keep
                                        the process transparent, we would like to guide you through our entire
                                        information collection process. This privacy policy and all its clauses are
                                        applicable to www.washingxpress.com which is a laundry, Dry-Cleaning and
                                        home-cleaning services provider platform, completely owned and operated by
                                        Rondella Marketing Private Limited. Please go through the privacy policy to
                                        fully understand our information gathering and dissemination practices. It is
                                        understood that by using our website www.washingxpress.com, you consent to the
                                        data gathering practices used anywhere on our website.
                                    </p>
                                </div>
                            </div>
                            <div class="hr-1 bg-black opacity-0 mt-30 mb-30"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left">
                                    <h2 class="fs-28 f-700 mb-5">Important Notes:</h2>
                                    <p class="mb-0">This privacy policy is subject to change at any time without notice.
                                        It is our sincere request that you review our website on a periodic basis to
                                        keep yourself apprised of the privacy policy. By visiting this website, you are
                                        agreeing to be bound by the terms and conditions specified in the Privacy
                                        Policy. If you do not agree please do not use or access our Website. By mere use
                                        of the Website, you expressly consent to our use and disclosure of your personal
                                        information in accordance with this Privacy Policy. This Privacy Policy is
                                        incorporated into and subject to the Terms of Use.</p>

                                </div>
                            </div>
                            <div class="hr-1 bg-black opacity-0 mt-30 mb-30"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 1 – COLLECTION OF PERSONAL DETAILS AND RELATED
                                        INFORMATION</h2>
                                    <p class="mb-0">Personal Data:
                                        We collect personal data from you when you voluntarily provide such information,
                                        such as when you contact us to place order for our services or to inquire about
                                        any information, respond to one of our surveys, which typically includes your:
                                    </p>
                                    <p class="mb-0">o Name;</p>
                                    <p class="mb-0">o Telephone Number</p>
                                    <p class="mb-0">o Email Address</p>
                                    <p class="mb-0">o House Address</p>
                                    <p class="mb-0">o Information about your home which you give us</p>
                                    <p class="mb-0">o Your payment details</p>
                                    <p class="mb-0">o Your IP address and</p>
                                    <p class="mb-0">o Any other personal information which you give us in connection
                                        with the Services.</p>
                                    <p class="mb-0">o Wherever we collect personal data we make an effort to provide a
                                        link to this Privacy Policy. If you send us personal correspondence, such as
                                        emails or letters, we may collect such information into a file specific to you.
                                    </p>
                                </div>
                            </div>
                            <div class="hr-1 bg-black opacity-0 mt-30 mb-30"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">URLs:</h2>
                                    <p class="mb-0">In general, You can browse our website without telling us who You
                                        are or revealing any personal information about yourself. Once you give us your
                                        personal information, you are not anonymous to us. Where possible, we indicate
                                        which fields are required and which fields are optional. You always have the
                                        option to not provide information for the fields that are optional. We may
                                        automatically track certain information about you based upon your behavior on
                                        Our Website. We use this information to do internal research on our users'
                                        demographics, interests, and behavior to better understand, protect and serve
                                        our users. This information is compiled and analyzed on an aggregated basis.
                                        This information may include the URL that you just came from (whether this URL
                                        is on our Website or not), which URL you next go to (whether this URL is on Our
                                        Website or not), your browser information, and your IP address. </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">Cookies:</h2>
                                    <p class="mb-0">We use data collection devices such as "cookies" on certain pages of
                                        the Website to help analyze our web page flow, measure promotional
                                        effectiveness, and promote trust and safety. "Cookies" are small files placed on
                                        your hard drive that assist us in providing our services. We offer certain
                                        features that are only available through the use of a "cookie". Most cookies are
                                        "session cookies," meaning that they are automatically deleted from your hard
                                        drive at the end of a session. You are always free to decline our cookies if
                                        your browser permits. Additionally, you may encounter "cookies" or other similar
                                        devices on certain pages of the Website that are placed by third parties. We do
                                        not control the use of cookies by third parties. We also use HTML5 Local Storage
                                        object to save information about user session and preferences Wherever We
                                        collect personal data we make an effort to provide a link to this Privacy
                                        Policy. If you send us personal correspondence, such as emails or letters, we
                                        may collect such information into a file specific to you.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">Payment Information:</h2>
                                    <p class="mb-0">If You transact with Us, We collect some additional information,
                                        such as a billing address, a credit / debit card number and a credit / debit
                                        card expiration date and/ or other payment instrument details and tracking
                                        information from cheques or money orders.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 2: WHAT DO WE DO WITH YOUR INFORMATION?</h2>
                                    <p class="mb-0">2.1 We use personal information to provide the delivery of our
                                        services to you. To the extent we use your personal information to market to
                                        You, We will provide you the ability to opt-out of such uses. We use your
                                        personal information to resolve disputes; troubleshoot problems; help promote a
                                        safe transaction; collect money; measure consumer interest in Our services,
                                        inform You about online and offline offers, services and updates; customize your
                                        experience; detect and protect Us against error, fraud and other criminal
                                        activity; enforce Our terms and conditions; and as otherwise described to You at
                                        the time of collection.</p>
                                    <p class="mb-0">2.2 In Our efforts to continually improve our service offerings, we
                                        collect and analyze demographic and profile data about Our Users' activity on
                                        Our Website. We identify and use your IP address to help diagnose problems with
                                        our server, and to administer Our Website. Your IP address is also used to help
                                        identify you and to gather broad demographic information.</p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 3: CONSENT</h2>
                                    <p class="mb-0">3.1 When You provide Us with personal information to complete a
                                        transaction, verify your credit card, place an order, arrange for a delivery or
                                        return a purchase, it is deemed that You have consented to the use of your
                                        personal information by Us to carry out the transaction as requested.</p>
                                    <p class="mb-0">3.2 In the course of business, if your personal information for any
                                        secondary reason, we shall specify the reason for requiring such information.
                                        Upon such request, you will have the option to refrain from revealing such
                                        information to us.</p>
                                    <p class="mb-0">3.3 If after you consent, either impliedly or expressly, for your
                                        personal information to be used by Us, You change your mind, you may withdraw
                                        your consent for us to contact you, for the continued collection, use or
                                        disclosure of your information, at any time. Such withdrawal of consent shall be
                                        communicated to us through an email at support@washingxpress.com</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 4: DISCLOSURE OF PERSONAL INFORMATION</h2>
                                    <p class="mb-0">4.1 We may share personal information with our other corporate
                                        entities and affiliates to help detect and prevent identity theft, fraud and
                                        other potentially illegal acts; correlate related or multiple accounts to
                                        prevent abuse of our Website; and to facilitate joint or co-branded services
                                        where such services are provided by more than one corporate entity. Those
                                        entities and affiliates may not market to you as a result of such sharing unless
                                        You explicitly opt-in.</p>
                                    <p class="mb-0">4.2 We may disclose personal information of you if required to do so
                                        by law or in the good faith belief that such disclosure is reasonably necessary
                                        to respond to subpoenas, court orders, or other legal process. We may disclose
                                        personal information to law enforcement offices, third party rights owners, or
                                        others in the good faith belief that such disclosure is reasonably necessary to
                                        enforce our Privacy Policy; respond to claims that an advertisement, posting or
                                        other content violates the rights of a third party; or protect the rights,
                                        property or personal safety of our Users or the general public.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 5: PAYMENTS</h2>
                                    <p class="mb-0">o All direct payment gateways adhere to the standards set by PCI-DSS
                                        as managed by the PCI Security Standards Council, which is a joint effort of
                                        brands like Visa, MasterCard, American Express and Discover.</p>
                                    <p class="mb-0">o PCI-DSS requirements help ensure the secure handling of credit
                                        card information by our store and its service providers. </p>
                                    <p class="mb-0">o For more insight, you may also want to read Washing Xpress Terms
                                        and Conditions here.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 6: THIRD-PARTY SERVICES</h2>
                                    <p class="mb-0">6.1 We may engage the services of third parties to help us serve our
                                        customers better. In general, the third-party services providers engaged by us
                                        will only collect, use and disclose your information to the extent necessary to
                                        allow them to perform the services they provide to Us.</p>
                                    <p class="mb-0">6.2 However, certain third-party service providers, such as payment
                                        gateways and other payment transaction processors, have their own privacy
                                        policies in respect to the information We are required to provide to them for
                                        your purchase-related transactions and we recommend that You read their privacy
                                        policies so You can understand the manner in which your personal information
                                        will be handled by these third party service providers.</p>
                                    <p class="mb-0">6.3 In particular, remember that certain providers may be located in
                                        or have facilities that are located a different jurisdiction than either you or
                                        us. So if you elect to proceed with a transaction that involves the services of
                                        a third-party service provider, then your information may become subject to the
                                        laws of the jurisdiction(s) in which that service provider or its facilities are
                                        located.</p>
                                    <p class="mb-0">6.4 Once you leave our website or are redirected to a third-party
                                        website or application, You are no longer governed by this Privacy Policy or our
                                        website’s Terms of Service.</p>
                                    <p class="mb-0">6.5 When you click on third party links on Our Website, We are not
                                        responsible for the privacy practices of other sites and for the loss or
                                        consequential damage that may be caused to you and encourage You to read their
                                        privacy statements.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 7: SECURITY PRECAUTIONS</h2>
                                    <p class="mb-0">7.1 To protect your personal information, we take reasonable
                                        precautions and follow industry best practices to make sure it is not
                                        inappropriately lost, misused, accessed, disclosed, altered or destroyed.</p>
                                    <p class="mb-0">7.2 We use Security Sockets Layer (SSL) encryption technology to
                                        encrypt sensitive personal information before it travels over the internet.
                                        Credit card numbers are never stored on our database or servers.</p>
                                    <p class="mb-0">7.3 We need to caution you that the Washing Xpress Services could be
                                        vulnerable to hacking, virus attacks and your personal data may be at risk.
                                        Washing Xpress takes all the necessary and reasonable caution to protect the
                                        Washing Xpress Service and data.</p>
                                    <p class="mb-0">7.4 We use Rupay secure online payment system to process payments on
                                        our app and website. You can choose whether to save the card information on
                                        Rupay during the payment process. Your information collected by Rupay secure
                                        online payment system is governed by Rupay privacy policy.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 8: ADVERTISEMENTS</h2>
                                    <p class="mb-0">8.1 On the Washing Xpress App and/or the Website and/or, Washing
                                        Xpress might post advertisements provided by Advertisers. These Advertisers
                                        might set mobile device id on their Apps. Washing Xpress is not responsible for
                                        any of these Advertisers. You on your entire risk and volition are advised to
                                        deal with the Advertisers if you intend to. By allowing such advertisements
                                        Washing Xpress do not recommend or market or warranty the Advertisers, quality,
                                        commitment, deliverables, genuineness and Advertisers commitment to protect your
                                        Personal Information.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 9: AGE OF CONSENT</h2>
                                    <p class="mb-0">9.1 By using this site, you represent that you are at least the age
                                        of majority in your state or province of residence and you have given us your
                                        consent to allow any of your minor dependents to use this site.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 10: THIRD PARTY SERVICES</h2>
                                    <p class="mb-0">You can log into our Website/App through your Google/Gmail account.
                                        In such a case, you must enter the email address and password that of your Gmail
                                        account. We will ask that you grant us permission to access and collect your
                                        basic information (this includes your name, profile picture, gender, networks,
                                        user IDs, list of friends, date of birth, email address, and any other
                                        information you have set to public on your account). If you allow us to have
                                        access to this information, then we will have access to this information even if
                                        you have chosen not to make that information public.
                                        We store the information that we receive from Google account with other
                                        information that we collect from you or receive about you.
                                        Google controls the information it collects from you. For information about how
                                        Google may use and disclose your information, including any information you make
                                        public, please consult Google privacy policy. We have no control over how any
                                        third party site uses or discloses the personal information it collects about
                                        you.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">SECTION 11: CHANGES TO THIS PRIVACY POLICY</h2>
                                    <p class="mb-0">11.1 We reserve the right to modify this privacy policy at any time,
                                        so please review it frequently. Changes and clarifications will take effect
                                        immediately upon their posting on the Website. If we make material changes to
                                        this policy, we will notify you here that it has been updated, so that you are
                                        aware of what information we collect, how we use it, and under what
                                        circumstances, if any, we use and/or disclose it.</p>
                                    <p class="mb-0">11.2 If our Website is acquired or merged with another company, your
                                        information may be transferred to the new owners so that we may continue to sell
                                        services to you.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-10 offset-lg-1">
                            <div class="row mt-25">
                                <div class="col-md-12 text-left ">
                                    <h2 class="fs-28 f-700 mb-5">CONTACT INFORMATION</h2>
                                    <p class="mb-0">For any query, grievance, complaint or any other information that
                                        may be required by You, You may contact Our Privacy Compliance Officer at
                                        Washing Xpress and We shall ensure that We help resolve the same within a period
                                        of 72 (seventy two) hours. You have any questions about this Privacy Policy, the
                                        practices of this site, or your dealings with this site, please contact us at:

                                        <br><br>RONDELLA LAUNDROMAT PVT. LTD.
                                        <br>436, DLF PRIME TOWERS F-79 &amp; 80,
                                        <br>OKHLA PHASE-I, NEW DELHI-110020
                                        <br>Tel: +91 88733-88111
                                        <br>support@washingxpress.com
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>  
    
</div>

@include('layouts.front-footer')
@endsection